//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenGrade.gStr", typeof(gStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Not Set.
        /// </summary>
        internal static string gsBoundaryNotSet {
            get {
                return ResourceManager.GetString("gsBoundaryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Too Small To Create a Headland.
        /// </summary>
        internal static string gsBoundaryTooSmall {
            get {
                return ResourceManager.GetString("gsBoundaryTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Button Again to Stop.
        /// </summary>
        internal static string gsClickButtonAgainToStop {
            get {
                return ResourceManager.GetString("gsClickButtonAgainToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Field.
        /// </summary>
        internal static string gsCloseField {
            get {
                return ResourceManager.GetString("gsCloseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Field First.
        /// </summary>
        internal static string gsCloseFieldFirst {
            get {
                return ResourceManager.GetString("gsCloseFieldFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Boundary First.
        /// </summary>
        internal static string gsCreateBoundaryFirst {
            get {
                return ResourceManager.GetString("gsCreateBoundaryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Has Begun.
        /// </summary>
        internal static string gsDrawingHasBegun {
            get {
                return ResourceManager.GetString("gsDrawingHasBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ft.
        /// </summary>
        internal static string gsFeet {
            get {
                return ResourceManager.GetString("gsFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Is Open.
        /// </summary>
        internal static string gsFieldIsOpen {
            get {
                return ResourceManager.GetString("gsFieldIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Not Open.
        /// </summary>
        internal static string gsFieldNotOpen {
            get {
                return ResourceManager.GetString("gsFieldNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your GPS source off?.
        /// </summary>
        internal static string gsIsGPSOff {
            get {
                return ResourceManager.GetString("gsIsGPSOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS.
        /// </summary>
        internal static string gsNoGPS {
            get {
                return ResourceManager.GetString("gsNoGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Guidance Lines.
        /// </summary>
        internal static string gsNoGuidanceLines {
            get {
                return ResourceManager.GetString("gsNoGuidanceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** No Sentence Data ***.
        /// </summary>
        internal static string gsNoSentenceData {
            get {
                return ResourceManager.GetString("gsNoSentenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string gsOff {
            get {
                return ResourceManager.GetString("gsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will exit. Please Restart.
        /// </summary>
        internal static string gsProgramExitAndRestart {
            get {
                return ResourceManager.GetString("gsProgramExitAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Field.
        /// </summary>
        internal static string gsStartNewField {
            get {
                return ResourceManager.GetString("gsStartNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on Contour or Make AB Line.
        /// </summary>
        internal static string gsTurnOnContourOrABLine {
            get {
                return ResourceManager.GetString("gsTurnOnContourOrABLine", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to NTRIP.
        /// </summary>
        internal static string gsNTRIP
        {
            get
            {
                return ResourceManager.GetString("gsNTRIP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Client Not Set Up.
        /// </summary>
        internal static string gsNTRIPClientNotSetUp
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPClientNotSetUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Client Settings.
        /// </summary>
        internal static string gsNTRIPClientSettings
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPClientSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Not Connected.
        /// </summary>
        internal static string gsNTRIPNotConnected
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPNotConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Not Connected, Retrying.
        /// </summary>
        internal static string gsNTRIPNotConnectedRetrying
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPNotConnectedRetrying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Not Connected to Send GGA.
        /// </summary>
        internal static string gsNTRIPNotConnectedToSendGGA
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPNotConnectedToSendGGA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Off.
        /// </summary>
        internal static string gsNTRIPOff
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP On.
        /// </summary>
        internal static string gsNTRIPOn
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NTRIP Restarting.
        /// </summary>
        internal static string gsNTRIPRestarting
        {
            get
            {
                return ResourceManager.GetString("gsNTRIPRestarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click Start to Resume.
        /// </summary>
        internal static string gsClickStartToResume
        {
            get
            {
                return ResourceManager.GetString("gsClickStartToResume", resourceCulture);
            }
        
        }
        /// <summary>
        ///   Looks up a localized string similar to Resuming With New Settings.
        /// </summary>
        internal static string gsResumingWithNewSettings
        {
            get
            {
                return ResourceManager.GetString("gsResumingWithNewSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restarting and Reconnecting to Caster.
        /// </summary>
        internal static string gsRestartingAndReconnectingToCaster
        {
            get
            {
                return ResourceManager.GetString("gsRestartingAndReconnectingToCaster", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At Socket Connect.
        /// </summary>
        internal static string gsAtSocketConnect
        {
            get
            {
                return ResourceManager.GetString("gsAtSocketConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No IP Located.
        /// </summary>
        internal static string gsNoIPLocated
        {
            get
            {
                return ResourceManager.GetString("gsNoIPLocated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot Find .
        /// </summary>
        internal static string gsCannotFind
        {
            get
            {
                return ResourceManager.GetString("gsCannotFind", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        internal static string gsNetworking
        {
            get
            {
                return ResourceManager.GetString("gsNetworking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string gsPort
        {
            get
            {
                return ResourceManager.GetString("gsPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Broadcaster URL or IP.
        /// </summary>
        internal static string gsEnterBroadcasterURLOrIP
        {
            get
            {
                return ResourceManager.GetString("gsEnterBroadcasterURLOrIP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To UDP Port.
        /// </summary>
        internal static string gsToUDPPort
        {
            get
            {
                return ResourceManager.GetString("gsToUDPPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string gsUsername
        {
            get
            {
                return ResourceManager.GetString("gsUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string gsPassword
        {
            get
            {
                return ResourceManager.GetString("gsPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mount.
        /// </summary>
        internal static string gsMount
        {
            get
            {
                return ResourceManager.GetString("gsMount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GGA Interval (secs).
        /// </summary>
        internal static string gsGGAIntervalSecs
        {
            get
            {
                return ResourceManager.GetString("gsGGAIntervalSecs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm IP.
        /// </summary>
        internal static string gsConfirmIP
        {
            get
            {
                return ResourceManager.GetString("gsConfirmIP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current GPS Fix:.
        /// </summary>
        internal static string gsCurrentGPSFix
        {
            get
            {
                return ResourceManager.GetString("gsCurrentGPSFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send To Manual Fix.
        /// </summary>
        internal static string gsSendToManualFix
        {
            get
            {
                return ResourceManager.GetString("gsSendToManualFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set to 0 for Serial.
        /// </summary>
        internal static string gsSetToZeroForSerial
        {
            get
            {
                return ResourceManager.GetString("gsSetToZeroForSerial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Source Table.
        /// </summary>
        internal static string gsGetSourceTable
        {
            get
            {
                return ResourceManager.GetString("gsGetSourceTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to * Restart Required.
        /// </summary>
        internal static string gsRestartRequired
        {
            get
            {
                return ResourceManager.GetString("gsRestartRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0 = Off.
        /// </summary>
        internal static string gsZeroEqualsOff
        {
            get
            {
                return ResourceManager.GetString("gsZeroEqualsOff", resourceCulture);
            }
        }

    }
}
