//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Remote : global::System.Configuration.ApplicationSettingsBase {
        
        private static Remote defaultInstance = ((Remote)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Remote())));
        
        public static Remote Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle Auto Cut")]
        public string aBtnFunc {
            get {
                return ((string)(this["aBtnFunc"]));
            }
            set {
                this["aBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open Gps Data")]
        public string bBtnFunc {
            get {
                return ((string)(this["bBtnFunc"]));
            }
            set {
                this["bBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle Survey")]
        public string xBtnFunc {
            get {
                return ((string)(this["xBtnFunc"]));
            }
            set {
                this["xBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset Blade Offset")]
        public string yBtnFunc {
            get {
                return ((string)(this["yBtnFunc"]));
            }
            set {
                this["yBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Increase Blade Offset")]
        public string upBtnFunc {
            get {
                return ((string)(this["upBtnFunc"]));
            }
            set {
                this["upBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Decrease Blade Offset")]
        public string downBtnFunc {
            get {
                return ((string)(this["downBtnFunc"]));
            }
            set {
                this["downBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle Tabs")]
        public string rightBtnFunc {
            get {
                return ((string)(this["rightBtnFunc"]));
            }
            set {
                this["rightBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save Cut")]
        public string leftBtnFunc {
            get {
                return ((string)(this["leftBtnFunc"]));
            }
            set {
                this["leftBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open Job")]
        public string startBtnFunc {
            get {
                return ((string)(this["startBtnFunc"]));
            }
            set {
                this["startBtnFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int aBtn {
            get {
                return ((int)(this["aBtn"]));
            }
            set {
                this["aBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int bBtn {
            get {
                return ((int)(this["bBtn"]));
            }
            set {
                this["bBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int xBtn {
            get {
                return ((int)(this["xBtn"]));
            }
            set {
                this["xBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int yBtn {
            get {
                return ((int)(this["yBtn"]));
            }
            set {
                this["yBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int upBtn {
            get {
                return ((int)(this["upBtn"]));
            }
            set {
                this["upBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int downBtn {
            get {
                return ((int)(this["downBtn"]));
            }
            set {
                this["downBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int leftBtn {
            get {
                return ((int)(this["leftBtn"]));
            }
            set {
                this["leftBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int rightBtn {
            get {
                return ((int)(this["rightBtn"]));
            }
            set {
                this["rightBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int startBtn {
            get {
                return ((int)(this["startBtn"]));
            }
            set {
                this["startBtn"] = value;
            }
        }
    }
}
