//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-64")]
        public double setCam_pitch {
            get {
                return ((double)(this["setCam_pitch"]));
            }
            set {
                this["setCam_pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM GPS...")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int setPort_baudRate {
            get {
                return ((int)(this["setPort_baudRate"]));
            }
            set {
                this["setPort_baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point setWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["setWindow_Location"]));
            }
            set {
                this["setWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1016, 839")]
        public global::System.Drawing.Size setWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["setWindow_Size"]));
            }
            set {
                this["setWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Maximized {
            get {
                return ((bool)(this["setWindow_Maximized"]));
            }
            set {
                this["setWindow_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Minimized {
            get {
                return ((bool)(this["setWindow_Minimized"]));
            }
            set {
                this["setWindow_Minimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM Section...")]
        public string setPort_portNameGradeControl {
            get {
                return ((string)(this["setPort_portNameGradeControl"]));
            }
            set {
                this["setPort_portNameGradeControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasRateRelayConnected {
            get {
                return ((bool)(this["setPort_wasRateRelayConnected"]));
            }
            set {
                this["setPort_wasRateRelayConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isMetric {
            get {
                return ((bool)(this["setMenu_isMetric"]));
            }
            set {
                this["setMenu_isMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isGridOn {
            get {
                return ((bool)(this["setMenu_isGridOn"]));
            }
            set {
                this["setMenu_isGridOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isLightbarOn {
            get {
                return ((bool)(this["setMenu_isLightbarOn"]));
            }
            set {
                this["setMenu_isLightbarOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setF_CurrentDir {
            get {
                return ((string)(this["setF_CurrentDir"]));
            }
            set {
                this["setF_CurrentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public byte setF_FieldColorR {
            get {
                return ((byte)(this["setF_FieldColorR"]));
            }
            set {
                this["setF_FieldColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public byte setF_FieldColorG {
            get {
                return ((byte)(this["setF_FieldColorG"]));
            }
            set {
                this["setF_FieldColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public byte setF_FieldColorB {
            get {
                return ((byte)(this["setF_FieldColorB"]));
            }
            set {
                this["setF_FieldColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte setF_SectionColorR {
            get {
                return ((byte)(this["setF_SectionColorR"]));
            }
            set {
                this["setF_SectionColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public byte setF_SectionColorG {
            get {
                return ((byte)(this["setF_SectionColorG"]));
            }
            set {
                this["setF_SectionColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public byte setF_SectionColorB {
            get {
                return ((byte)(this["setF_SectionColorB"]));
            }
            set {
                this["setF_SectionColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setF_IsWorkSwitchActiveLow {
            get {
                return ((bool)(this["setF_IsWorkSwitchActiveLow"]));
            }
            set {
                this["setF_IsWorkSwitchActiveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchEnabled {
            get {
                return ((bool)(this["setF_IsWorkSwitchEnabled"]));
            }
            set {
                this["setF_IsWorkSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM AS")]
        public string setPort_portNameAutoSteer {
            get {
                return ((string)(this["setPort_portNameAutoSteer"]));
            }
            set {
                this["setPort_portNameAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasAutoSteerConnected {
            get {
                return ((bool)(this["setPort_wasAutoSteerConnected"]));
            }
            set {
                this["setPort_wasAutoSteerConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setIMU_pitchZero {
            get {
                return ((double)(this["setIMU_pitchZero"]));
            }
            set {
                this["setIMU_pitchZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setIMU_rollZero {
            get {
                return ((double)(this["setIMU_rollZero"]));
            }
            set {
                this["setIMU_rollZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isLogNMEA {
            get {
                return ((bool)(this["setMenu_isLogNMEA"]));
            }
            set {
                this["setMenu_isLogNMEA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Ko {
            get {
                return ((byte)(this["setAS_Ko"]));
            }
            set {
                this["setAS_Ko"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public byte setAS_Kp {
            get {
                return ((byte)(this["setAS_Kp"]));
            }
            set {
                this["setAS_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_Ki {
            get {
                return ((byte)(this["setAS_Ki"]));
            }
            set {
                this["setAS_Ki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public byte setAS_Kd {
            get {
                return ((byte)(this["setAS_Kd"]));
            }
            set {
                this["setAS_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public byte setAS_steerAngleOffset {
            get {
                return ((byte)(this["setAS_steerAngleOffset"]));
            }
            set {
                this["setAS_steerAngleOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTripAlarm {
            get {
                return ((double)(this["setF_UserTripAlarm"]));
            }
            set {
                this["setF_UserTripAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTotalArea {
            get {
                return ((double)(this["setF_UserTotalArea"]));
            }
            set {
                this["setF_UserTotalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte setAS_minSteerPWM {
            get {
                return ((byte)(this["setAS_minSteerPWM"]));
            }
            set {
                this["setAS_minSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_maxIntegral {
            get {
                return ((byte)(this["setAS_maxIntegral"]));
            }
            set {
                this["setAS_maxIntegral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_countsPerDegree {
            get {
                return ((byte)(this["setAS_countsPerDegree"]));
            }
            set {
                this["setAS_countsPerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isPureOn {
            get {
                return ((bool)(this["setMenu_isPureOn"]));
            }
            set {
                this["setMenu_isPureOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int setIP_thisPort {
            get {
                return ((int)(this["setIP_thisPort"]));
            }
            set {
                this["setIP_thisPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.155")]
        public string setIP_AntennaIP {
            get {
                return ((string)(this["setIP_AntennaIP"]));
            }
            set {
                this["setIP_AntennaIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public int setIP_AntennaPort {
            get {
                return ((int)(this["setIP_AntennaPort"]));
            }
            set {
                this["setIP_AntennaPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.255")]
        public string setIP_gradeControlIP {
            get {
                return ((string)(this["setIP_gradeControlIP"]));
            }
            set {
                this["setIP_gradeControlIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7777")]
        public int setIP_gradeControlPort {
            get {
                return ((int)(this["setIP_gradeControlPort"]));
            }
            set {
                this["setIP_gradeControlPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSimulatorOn {
            get {
                return ((bool)(this["setMenu_isSimulatorOn"]));
            }
            set {
                this["setMenu_isSimulatorOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53.436026")]
        public double setSim_lastLat {
            get {
                return ((double)(this["setSim_lastLat"]));
            }
            set {
                this["setSim_lastLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111.160047")]
        public double setSim_lastLong {
            get {
                return ((double)(this["setSim_lastLong"]));
            }
            set {
                this["setSim_lastLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSkyOn {
            get {
                return ((bool)(this["setMenu_isSkyOn"]));
            }
            set {
                this["setMenu_isSkyOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string set_culture {
            get {
                return ((string)(this["set_culture"]));
            }
            set {
                this["set_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double setF_minFixStep {
            get {
                return ((double)(this["setF_minFixStep"]));
            }
            set {
                this["setF_minFixStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte set_KpGain {
            get {
                return ((byte)(this["set_KpGain"]));
            }
            set {
                this["set_KpGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte set_KiGain {
            get {
                return ((byte)(this["set_KiGain"]));
            }
            set {
                this["set_KiGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28")]
        public byte set_KdGain {
            get {
                return ((byte)(this["set_KdGain"]));
            }
            set {
                this["set_KdGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte set_RetDeadband {
            get {
                return ((byte)(this["set_RetDeadband"]));
            }
            set {
                this["set_RetDeadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte set_ExtDeadband {
            get {
                return ((byte)(this["set_ExtDeadband"]));
            }
            set {
                this["set_ExtDeadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte set_ValveType {
            get {
                return ((byte)(this["set_ValveType"]));
            }
            set {
                this["set_ValveType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNH")]
        public string set_ValveName {
            get {
                return ((string)(this["set_ValveName"]));
            }
            set {
                this["set_ValveName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int set_AutoDepth {
            get {
                return ((int)(this["set_AutoDepth"]));
            }
            set {
                this["set_AutoDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V-.-.-")]
        public string set_GcModVersion {
            get {
                return ((string)(this["set_GcModVersion"]));
            }
            set {
                this["set_GcModVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V-.-.-")]
        public string set_AntModVersion {
            get {
                return ((string)(this["set_AntModVersion"]));
            }
            set {
                this["set_AntModVersion"] = value;
            }
        }
    }
}
